version: 1
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Styles"
      regexp: '^.*?style(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Code Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: "Tests"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: "Builds"
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 7
    - title: "Continuous Integrations"
      regexp: '^.*?ci(\([[:word:]]+\))??!?:.+$'
      order: 8
    - title: "Chores"
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 9
    - title: "Reverts"
      regexp: '^.*?revert(\([[:word:]]+\))??!?:.+$'
      order: 10
    - title: Others
      order: 999
